name: Release Scrapix
# Trigger the Github action when the CHANGELOG.md file is changed (on New release)
on:
  push:
    branches: 
      - 'master'

jobs:
  release:   #release job 
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout"
        uses: "actions/checkout@master"
        with: 
          fetch-depth: 0 

      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with: 
          node-version: 12.x 
          registry-url: https://registry.npmjs.org

      # - name: "Install dependencies"
      #   run: npm install --production

      # - name: "Build"
      #   run: npm run build

      - name: "Publish package"
        run: npm publish --access public 
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      # TODO: Action for tests 




